travis:
  secure:
    BINSTAR_TOKEN: AVCYWGshJr2CJ+o5RTXx1w6+JRuGbbkz1RR+C/ZCZkPd2ACLUflFTzPBIxs6WBzBQ67F54d0xeiDE43wUxJ6Ufx2dnmqVJrtSeqlpklybk3WzVOi4vIS/S+bgEilPlmGrrSoH/4ZL9GD2Y/19/47oEPX9uz5KD/LDtjUD9xYOV1IgBOirkjwR0fNyhmAomMGk1RwoX8hydtC4aUPGbT4CIXeWn6LUx9/IFUzXLlvSX0PMUqQtgbmlrm3FxgPx2lpSOcyr462yRY82z3ThqQQeyYT74aQ9JYbS54weRhm3tUaNnhockuBQSKtYTrm4a0isFV4zccl3XHXtQ8gIoXREatZxD43mu3UP5+jGI+EbTOFOD1arvDa3c5V5MyZU2AAbveYtotS2jnnU5E3jWx1Ye06TiJoEOPPmy4CRwNu+HbKncHyaPVxniH5lXX2dBB6cPL2EiZVTSAGC3ioFq1lFtV4JChyfrS2gHlrFz1/F6NyRmwTlaUUuZTv3T08m5/c9NPkUy0UmkcHRy0JOYGPz55DtCmf+Gn17sAH+6hKP+kpnTth1dz3sCgXP95Xcm/Jwlby38+PH5EGgfDLZt43IuWeRTrJoeOYntD4SBdejoqEoR1DtgxnRDmFEpBCU40SYk9iMjeL52FfxNismK/haJAcnlToiTHwBGq32dct0x8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
