travis:
  secure:
    BINSTAR_TOKEN: FGBGu+H5EnjIotN+0Ty9iMc0srox1pYUyylCozWl9ftVkf/bitejinoToRnBwTU9woMwXJRx+E8LqFgSJVwB/7PA73AqLuGhIVeBvzc3+fkvdjVyDYr6EGD+06RL9bW0A7Cjxw8ZpCnSIvGWRKSQV5f3+jtT2+fsqCluHZRBhjbJalsrLWG4CpQppMqUrPDmWmYdOoINCeJ9Cxqa4V+C3h49oM/9uymPEF8HKgDF3FIcaUDtZyvcSeZvK851kIqPc8mOzYz0dNdOI8nAg+1G/xjLTADZ59qPFTXHB/AilrAyHw6m7jb7CaH++Vahq+nb31NlnptttsHe/sVJ4Ybb6CT4vMKDKj34Op+fwP2wO2tTrmvoiimOcXw3EHrrsouENyTaEmXEZAefx4dzPX4ibbWCW/pKKwlcERo+gI0k86I67K0hD/qFNFhOdLsUPuQNAJAPNxk61Wgt7dNlibIViAx08sichNwhzpShHS8ZyOkSbnEf0E/ACZjMIx7hr/sHondlerIYu+8Fpz8/yfts7oGvu3WxOhNfbum5gUZvBlYEVMrHP4FjuK3q7rl4tV1CejOf/Ew7tffgX21OME43DOEmJq91dKO3jX2es7ETUKmT61y3SOTtf2u+EU1Kw8xF/nThMjPAb4BX7CzEwvIGlCkTFg3Nqqk3UHHCG1nl2oM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
